In [1]:
from utils.lib_util import *
from utils.data_util import *

from torch.utils.data import DataLoader

batch_size = 32

dataset, _, _, _, _ = get_dataset()
dataloader = DataLoader(dataset, batch_size, shuffle=True)

def tensor_merge(tensor_list):
    if len(tensor_list) == 1:
        return tensor_list[0].unsqueeze(0)
    tensor = torch.stack((tensor_list[0], tensor_list[1]))
    for tensor_ in tensor_list[2:]:
        tensor = torch.cat((tensor, tensor_.unsqueeze(0)))
    return tensor


def data_loader(dataset_list, batch_size, shuffle=False, device='cpu'):
    num_data = len(dataset_list)
    data = [dataset[0] for dataset in dataset_list]
    target = torch.tensor([dataset[1] for dataset in dataset_list])
    idxs = [i for i in range(num_data)]
    if shuffle:
        random.shuffle(idxs)
    num_dataloader = num_data // batch_size
    if num_data % batch_size:
        num_dataloader += 1
    for i in range(num_dataloader):
        idx = i * batch_size
        data_return = tensor_merge(data[idx: idx+batch_size])
        target_return = target[idx: idx+batch_size]
        yield (data_return.to(device), target_return.to(device))

In [2]:
for i in dataloader:
    pass

In [3]:
for i in data_loader(dataset, batch_size, shuffle=True):
    pass

In [39]:
import numpy
import torch

a = torch.tensor([1, 2, 3])
b = 1
c = [1, 2, 3]
d = [a, b, c]

numpy.savez('./test.npz', a, b, c)

In [42]:
import numpy
import os

file = numpy.load('./test.npz', allow_pickle=True)
print(file['arr_2'])

[1 2 3]


In [1]:
import numpy

file_path = './data/dealed-data/mnist_algo_3/alpha_0.5_T_8/server_commu_20_client_commu_10_client_train_10_batch_size_200_num_all_client_9_num_all_server_3_num_client_data_1000_num_public_data_50_proportion_0.8.npz'
data = numpy.load(file_path, allow_pickle=True)['arr_0']

print(data)

{'args': Namespace(dataset='mnist', alpha=0.5, T=8, num_all_client=9, num_all_server=3, batch_size=200, num_client_data=1000, num_server_commu=20, num_client_commu=10, num_client_train=10, num_public_train=10, model_select=1, algorithm=3, num_public_data=50, proportion=0.8, server_client=[[0, 1, 2], [3, 4, 5], [6, 7, 8]], neighbor_server=[[1], [2], [0]], device='cuda'), 'server_model': {0: None, 1: None, 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None, 9: [CNN(
  (conv1): Sequential(
    (0): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): AvgPool2d(kernel_size=2, stride=2, padding=0)
  )
  (conv2): Sequential(
    (0): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): AvgPool2d(kernel_size=2, stride=2, padding=0)
  )
  (full_con): Sequential(
    (0): Linear(in_features=400, out_features=64, bias=True)
    (1): ReLU(inplace=True)
  )
  (output): Linear(in_features=64, out_features=10, bias=True)
), 

In [ ]:
import os
import argparse

import matplotlib.pyplot as plt

from utils.lib_util import *

args = get_args()
args.dataset = 'mnist'
args.algorithm = 3
args.num_server_commu = 30
args.num_client_commu = 5
args.num_client_train = 5
args.batch_size = 200
args.num_all_client = 9
args.num_all_server = 3
args.num_client_data = 1000
args.num_public_data = 50
args.proportion = 0.8

save_path = f'./data/dealed-data/{args.dataset}_algo_{args.algorithm}/alpha_{args.alpha}_T_{args.T}/'

# file_name = f'server_commu_{args.num_server_commu}_client_commu_{args.num_client_commu}_client_train_{args.num_client_train}_batch_size_{args.batch_size}_num_all_client_{args.num_all_client}_num_all_server_{args.num_all_server}_num_client_data_{args.num_client_data}_num_public_data_{args.num_public_data}_proportion_{args.proportion}.npz'

file_path = save_path + (
    f'server_commu_{args.num_server_commu}'
    f'_client_commu_{args.num_client_commu}'
    f'_client_train_{args.num_client_train}'
    f'_batch_size_{args.batch_size}'
    f'_num_all_client_{args.num_all_client}'
    f'_num_all_server_{args.num_all_server}'
    f'_num_client_data_{args.num_client_data}'
    f'_num_public_data_{args.num_public_data}'
    f'_proportion_{args.proportion}.npz')

print(file_path)


In [ ]:
import torch

data = torch.load('./server_model.pt')
print(len(data))

a = data[0].state_dict()
b = data[1].state_dict()

print(len(list(a.keys())))
key = list(a.keys())[1]
print(key)
print(a[key])
print(b[key])
print(a[key] == b[key])

data = torch.load('./client_model.pt')
print(len(data))

a = data[0].state_dict()
b = data[1].state_dict()
c = data[2].state_dict()
d = data[3].state_dict()

print(len(list(a.keys())))
key = list(a.keys())[1]
print(key)
print(a[key])
print(b[key])
print(a[key] == c[key])

2
8
conv1.0.bias
tensor([-0.1044,  0.0577,  0.0539,  0.1454, -0.2464,  0.2036], device='cuda:0')
tensor([-0.1167,  0.0541,  0.0558,  0.1468, -0.2451,  0.2145], device='cuda:0')
tensor([False, False, False, False, False, False], device='cuda:0')
4
8
conv1.0.bias
tensor([-0.2810,  0.0607,  0.1299,  0.0136,  0.2965, -0.2470], device='cuda:0')
tensor([-0.2810,  0.0607,  0.1299,  0.0136,  0.2965, -0.2470], device='cuda:0')
tensor([False, False, False, False, False, False], device='cuda:0')


In [ ]:
import torch

data = torch.load('./data/dealed-data/mnist_algo_3/alpha_0.5_T_8/server_commu_2_client_commu_2_client_train_2_batch_size_10_num_all_client_4_num_all_server_2_num_client_data_100_num_public_data_50_proportion_0.8.pt')

m = data['server_model'][1]

a = m[0].state_dict()
b = m[1].state_dict()
key = list(a.keys())[1]
print(a[key] == b[key])

tensor([False, False, False, False, False, False], device='cuda:0')


In [ ]:
import torch

data = torch.load('./data/dealed-data/mnist_algo_3/alpha_0.5_T_8/server_commu_2_client_commu_2_client_train_2_batch_size_10_num_all_client_4_num_all_server_2_num_client_data_100_num_public_data_50_proportion_0.8.pt')

client_acc = data['client_acc']
print(client_acc)

[[0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459], [0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459, 0.10140703618526459], [0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637], [0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637, 0.10100502520799637]]
