In [1]:
import torch
import torchvision
import numpy

from torch.utils.data import Dataset, DataLoader

In [2]:
train_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=True,
    transform=torchvision.transforms.ToTensor(),   #将图片转化成取值[0,1]的Tensor用于网络处理, [H, W, C]转化成[C ,H, W]
    download=True
)
test_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=False,
    transform=torchvision.transforms.ToTensor()
)

In [3]:
data = train_dataset.data
print(type(data), data.size())
a_date = data[59999, :, :]
a_date = a_date.unsqueeze(0)
print(a_date, a_date.size())

<class 'torch.Tensor'> torch.Size([60000, 28, 28])
tensor([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,

In [4]:
label = train_dataset.targets
print(type(label), label.size())
a_date_label = label[1:2]
print(a_date_label, type(a_date_label), a_date_label.size())

<class 'torch.Tensor'> torch.Size([60000])
tensor([0]) <class 'torch.Tensor'> torch.Size([1])


In [5]:
class DealDataset(Dataset):
    def __init__(self, dataset, idx):
        self.dataset = dataset
        self.idx = idx
        self.len = len(idx)

    def __len__(self):
        return self.len

    def __getitem__(self, index):
        img, target = self.dataset[self.idx[index]]
        return img, target

dataset = DealDataset(train_dataset, [0, 1, 2, 3])
train_dataloader = DataLoader(dataset, batch_size=2)

data, b= train_dataloader
a_data, a_label = data
print(a_data, type(a_data), a_data.size())
print(a_label, type(a_label), a_label.size())

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]]) <class 'torch.Tensor'> torch.Size([2, 1, 28, 28])
tensor([5, 0]) <class 'torch.Tensor'> torch.Size([2])


In [ ]:
train_dataset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    transform=torchvision.transforms.ToTensor(),
    download=True
)

data = train_dataset.data[0]
print(data, type(data))
print(data.shape)